### ISSUE TITLE
max-function-body-length rule counts comment as function body length

### ISSUE THREAD

**Issue by aakashkharche04** [benderTheCrime/eslint-plugin-benderthecrime#7]
benderthecrime/max-function-body-length rule counts even the "// eslint-disable-next-line no-restricted-syntax" comment as part of function body length. This is should not be counted.

**Comment by benderTheCrime** [comment]
Thanks for raising this. However, as for the nature of the issue:

> benderthecrime/max-function-body-length rule counts even the "// eslint-disable-next-line no-restricted-syntax" comment as part of function body length. This is should not be counted.

this is objectively not true. In fact, the entire reason this rule exists is that v8 versions <6 effectively de-optimize functions that have a body of greater than 600 characters **inclusive of comments, whitespace, and any other characters in the body**.

For an example, please see this test.
